import re
from typing import List, Dict, Any, Union

"""
Utility functions for processing and extracting mathematical expressions
from OCR output.

This module provides tools to clean LaTeX strings and to identify,
extract, and replace mathematical content within raw text generated by OCR.
"""


def clean_latex(latex: str) -> str:
    """
    Fixes common issues in LaTeX strings, specifically double backslashes
    that might be produced by the LLM.

    Args:
        latex: The raw LaTeX string to be cleaned.

    Returns:
        The cleaned LaTeX string with corrected backslash usage.
    """
    latex = re.sub(r"\\\\([a-zA-Z])", r"\\\1", latex)
    latex = latex.replace("\\\\", "\\")
    return latex.strip()


def extract_math(raw_text: str) -> Dict[str, Union[str, List[str]]]:
    """
    Extracts mathematical expressions enclosed in <m>...</m> tags from a given text.

    It cleans the extracted LaTeX, filters out non-math content (e.g., LLM errors
    producing English words within math tags), and replaces math expressions
    with placeholders in the main text.

    Args:
        raw_text: The input text containing potential math expressions
                  enclosed in <m> and </m> tags.

    Returns:
        A dictionary containing:
            - "text" (str): The text with math expressions replaced by placeholders
                            like "$math[0]$".
            - "math" (list): A list of cleaned LaTeX strings for each extracted
                             math expression.
    """
    # Find all opening and closing tags
    opens: List[int] = [m.start() for m in re.finditer(r"<m>", raw_text)]
    closes: List[int] = [m.start() for m in re.finditer(r"</m>", raw_text)]

    math_expressions: List[str] = []
    result_text: str = raw_text

    # Regex to find <m>...</m> pairs, non-greedy, and allowing nested tags to be skipped
    pattern = re.compile(r"<m>((?:(?!</?m>).)+?)</m>", re.DOTALL)
    matches: List[re.Match] = list(pattern.finditer(raw_text))

    if not matches:
        # No valid math tags found — strip any broken tag fragments
        cleaned: str = re.sub(r"</?m>", "", raw_text)
        return {"text": cleaned.strip(), "math": []}

    # Process matches in reverse order to avoid issues with index changes
    for match in reversed(matches):
        latex: str = clean_latex(match.group(1))
        # Skip if it's mostly English words (LLM error)
        words: List[str] = latex.split()
        english_words: int = sum(
            1
            for w in words
            if re.match(r"^[a-zA-Z]{3,}$", w)
            and w.lower()
            not in (
                "sin",
                "cos",
                "tan",
                "log",
                "ln",
                "lim",
                "inf",
                "max",
                "min",
                "det",
                "dim",
                "mod",
                "gcd",
                "lcm",
                "exp",
            )
        )
        if len(words) > 2 and english_words > len(words) * 0.5:
            # More than half are plain English — not math, unwrap it
            result_text = (
                result_text[: match.start()]
                + match.group(1)
                + result_text[match.end() :]
            )
            continue

        idx: int = len(math_expressions)
        math_expressions.append(latex)
        result_text = (
            result_text[: match.start()]
            + f"$math[{idx}]$"
            + result_text[match.end() :]
        )

    math_expressions.reverse()  # Restore original order

    current: int = 0

    def reindex(m: re.Match) -> str:
        nonlocal current
        idx: int = current
        current += 1
        return f"$math[{idx}]$"

    # Reindex placeholders to be sequential after filtering
    result_text = re.sub(r"\$math\[\d+\]\$", reindex, result_text)

    # Remove any remaining partial or unmatched tags
    result_text = re.sub(r"</?m>", "", result_text)

    # Clean whitespace around placeholders and normalize multiple spaces
    result_text = re.sub(r"\s*(\$math\[\d+\]\$)\s*", r" \1 ", result_text)
    result_text = re.sub(r"  +", " ", result_text).strip()

    return {"text": result_text, "math": math_expressions}
